# Generated by Django 3.2.7 on 2021-10-05 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_price', models.FloatField()),
                ('tax_rate', models.FloatField(default=0.13)),
            ],
        ),
    ]
